
name: stm32-t12

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get update -y
    - name: install
      run: sudo apt-get install gcc-arm-none-eabi gcc -y
    - name: Building
      run: |
        make
