
name: stm32-t12

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update
      run: sudo apt-get update -y
    - name: install
      run: sudo apt-get install gcc-arm-none-eabi unzip wget -y
    - name: Building
      run: |
        wget -q http://web.muxi416.ga/stm32-t12.zip
        unzip -q stm32-t12.zip
        cd stm32-t12
        make
