
name: stm32-t12

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: sudo apt-get install gcc-arm-none-eabi unzip wget -y
    - name: Building
      run: |
        wget -q http://web.muxi416.ga/stm32-t12.zip
        unzip -q stm32-t12.zip
        cd stm32-t12
        make
    - name: Create and Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        #tag_name: ${{ github.ref }}
        #name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          oled1.hex 
