
name: stm32-t12

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install gcc for arm 
      run: sudo apt-get install gcc-arm-none-eabi -y
    - name: Run!
      env:
          THREAD: ${{ secrets.THREAD }}
          URL: ${{ secrets.URL }} 
      run: |
        gcc-arm-none-eabi
