
name: stm32-t12

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install gcc for arm 
      run: sudo apt-get install gcc-arm-none-eabi -y
    - name: Building
      run: |
        cd /oled1
        make
