
name: stm32-t12

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: sudo apt-get install gcc-arm-none-eabi unzip wget -y
    - name: Building
      run: |
        wget -q http://web.muxi416.ga/stm32-t12.zip
        unzip -q stm32-t12.zip
        cd stm32-t12
        make
        zip -r first.zip build/oled1.hex
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: test
        name: Release test
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          first.zip 
